main.py:
    simTime: 40
    timestep: 0.1

---
trajectory_eightshape_v1:
    c1x: 10
    c1y: 15
    c2x: 50
    c2y: 15
    R1: 10
    R2: 10
        #delta: "3.14/8" #adjust joint between Arc and Line Segments
    
    arrayStep: 0.0001
    theta1_limInf: "(3.14/2 - delta)" #Matlab: theta1 = (pi/2 - delta) : 0.0001 : ((3*pi)/2 + delta);
    theta1_limSup: "((3*3.14)/2 + delta)"

    theta2_limInf: "-(3.14/2 + delta)" #Matlab: theta2 = -(pi/2 + delta) : 0.0001 : (pi/2 + delta);
    theta2_limSup: "(3.14/2 + delta)"
---
environmentMap:
    plotSubfolderName: output_plots
---
plots_1:
    color: "blue"
    lineStyle: "-"
    lineWidth: 2
    plotRows: 1
    plotColumns: 2
...